# Generated by Django 3.2.8 on 2021-12-09 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactos', '0002_contacto_estado'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoOrden',
            fields=[
                ('IdEstado', models.SmallAutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('IdOrden', models.BigAutoField(primary_key=True, serialize=False)),
                ('DetalleSolicitud', models.CharField(max_length=200)),
                ('TipoSolicitud', models.CharField(max_length=200)),
                ('TipoReparacion', models.CharField(max_length=200)),
                ('Diagnostico', models.BooleanField(default=False)),
                ('Repuesto', models.BooleanField(default=False)),
                ('RevisionFisica', models.BooleanField(default=False)),
                ('Intervencion', models.BooleanField(default=False)),
                ('Scaner', models.BooleanField(default=False)),
                ('SolicitudRepuesto', models.BooleanField(default=False)),
                ('IdContacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactos.contacto')),
                ('IdEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.estadoorden')),
                ('IdVehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo')),
            ],
        ),
    ]
