# Generated by Django 3.2.8 on 2021-12-09 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('IdTipoSolicitud', models.SmallAutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='orden',
            name='TipoSolicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.tiposolicitud'),
        ),
    ]
